CREATE OR ALTER VIEW View_Meteo
AS
SELECT
    "ID OMM station" AS id_resort,
    "Date" AS date,
    "Direction du vent moyen 10 mn" AS wind_direction,
    "Vitesse du vent moyen 10 mn" AS wind_speed,
    "Température" AS temp_kelvin,
    "Humidité" AS humidity,
    "Hauteur de la base des nuages de l'étage inférieur" AS heigh_clouds,
    "Nom" AS name,
    "Température (°C)" AS temp_degree,
    "Altitude" AS altitude,
    "communes (name)"  AS commune_name,
    "communes (code)"  AS id_commune,
    "mois_de_l_annee" AS month,
    YEAR(Date) as year
FROM
    OPENROWSET(
        BULK 'files/donnees-synop-essentielles-omm.csv',
        DATA_SOURCE = 'root',
        FORMAT = 'CSV',
        PARSER_VERSION = '2.0',
        FIELDTERMINATOR = ';',
        FIRSTROW = 2
    )
    WITH(
        "ID OMM station" VARCHAR(10),
        "Date" DATETIME2,
        "Pression au niveau mer" FLOAT,
        "Variation de pression en 3 heures" FLOAT,
        "Type de tendance barométrique" FLOAT,
        "Direction du vent moyen 10 mn" FLOAT,
        "Vitesse du vent moyen 10 mn" FLOAT,
        "Température" FLOAT,
        "Point de rosée" FLOAT,
        "Humidité" FLOAT,
        "Visibilité horizontale" FLOAT,
        "Temps présent" FLOAT,
        "Temps passé 1" FLOAT,
        "Temps passé 2" FLOAT,
        "Nebulosité totale" FLOAT,
        "Nébulosité  des nuages de l' étage inférieur" FLOAT,
        "Hauteur de la base des nuages de l'étage inférieur" FLOAT,
        "Type des nuages de l'étage inférieur" FLOAT,
        "Type des nuages de l'étage moyen" FLOAT,
        "Type des nuages de l'étage supérieur" FLOAT,
        "Pression station" FLOAT,
        "Niveau barométrique" FLOAT,
        "Géopotentiel" FLOAT,
        "Variation de pression en 24 heures" FLOAT,
        "Température minimale sur 12 heures" FLOAT,
        "Température minimale sur 24 heures" FLOAT,
        "Température maximale sur 12 heures" FLOAT,
        "Température maximale sur 24 heures" FLOAT,
        "Température minimale du sol sur 12 heures" FLOAT,
        "Méthode de mesure Température du thermomètre mouillé" FLOAT,
        "Température du thermomètre mouillé" FLOAT,
        "Rafale sur les 10 dernières minutes" FLOAT,
        "Rafales sur une période" FLOAT,
        "Periode de mesure de la rafale" FLOAT,
        "Etat du sol" FLOAT,
        "Hauteur totale de la couche de neige, glace, autre au sol" FLOAT,
        "Hauteur de la neige fraîche" FLOAT,
        "Periode de mesure de la neige fraiche" FLOAT,
        "Précipitations dans la dernière heure" FLOAT,
        "Précipitations dans les 3 dernières heures" FLOAT,
        "Précipitations dans les 6 dernières heures" FLOAT,
        "Précipitations dans les 12 dernières heures" FLOAT,
        "Précipitations dans les 24 dernières heures" FLOAT,
        "Phénomène spécial 1" FLOAT,
        "Phénomène spécial 2" FLOAT,
        "Phénomène spécial 3" FLOAT,
        "Phénomène spécial 4" FLOAT,
        "Nébulosité couche nuageuse 1" FLOAT,
        "Type nuage 1" FLOAT,
        "Hauteur de base 1" FLOAT,
        "Nébulosité couche nuageuse 2" FLOAT,
        "Type nuage 2" FLOAT,
        "Hauteur de base 2" FLOAT,
        "Nébulosité couche nuageuse 3" FLOAT,
        "Type nuage 3" FLOAT,
        "Hauteur de base 3" FLOAT,
        "Nébulosité couche nuageuse 4" FLOAT,
        "Type nuage 4" FLOAT,
        "Hauteur de base 4" FLOAT,
        "Coordonnees" VARCHAR(255),
        "Nom" VARCHAR(255),
        "Type de tendance barométrique txt" VARCHAR(255),
        "Temps passé 1 txt" VARCHAR(255),
        "Temps présent txt" VARCHAR(255),
        "Température (°C)" FLOAT,
        "Température minimale sur 12 heures (°C)" FLOAT,
        "Température minimale sur 24 heures (°C)" FLOAT,
        "Température maximale sur 12 heures (°C)" FLOAT,
        "Température maximale sur 24 heures (°C)" FLOAT,
        "Température minimale du sol sur 12 heures (en °C)" FLOAT,
        "Latitude" FLOAT,
        "Longitude" FLOAT,
        "Altitude" FLOAT,
        "communes (name)" VARCHAR(255),
        "communes (code)" VARCHAR(10),
        "EPCI (name)" VARCHAR(255),
        "EPCI (code)" VARCHAR(100),
        "department (name)" VARCHAR(255),
        "department (code)" VARCHAR(10),
        "region (name)" VARCHAR(255),
        "region (code)" VARCHAR(10),
        "mois_de_l_annee" INT
    ) AS temp